#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /usr/bin/common.sh

cd /app || exit 1

log_info 'Starting backend ...'

if [ "${DEVELOPMENT:-}" = 'true' ]; then
	s6-setuidgid "$PUID:$PGID" yarn install
	exec s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;export CERTBOT_VERSION=$CERTBOT_VERSION;node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js"
else
	while :
	do
		s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;export CERTBOT_VERSION=$CERTBOT_VERSION;node --max_old_space_size=250 index.js 2>&1 | tee -a /tmp/backend_stdout.log"
		echo "RESTARTING at $(date)" >> /tmp/backend_stdout.log
		sleep 2
	done
fi
