#!/command/with-contenv bash
# shellcheck shell=bash

# This command reads the `NPM_ADMIN_PORT` env var and will fall
# back to 81 if this is not set or is not a number.

set -e

log_info 'Admin Port ...'

NPM_ADMIN_PORT="${NPM_ADMIN_PORT:-81}"
# ensure admin port is a number
if ! [[ "$NPM_ADMIN_PORT" =~ ^[0-9]+$ ]]; then
	echo "WARNING: NPM_ADMIN_PORT must be a number. Defaulting to 81" >&2
	NPM_ADMIN_PORT=81
fi

ADMINCFG="/etc/haproxy/conf.d/admin.cfg"

# Generate admin frontend/backend config
cat > "$ADMINCFG" <<EOF
# Auto-generated admin interface configuration
# Do not edit this file directly

frontend admin_http
    bind *:${NPM_ADMIN_PORT}
    mode http

    # Admin API
    acl is_api path_beg /api/
    use_backend backend_api if is_api

    # Frontend assets
    default_backend backend_frontend

backend backend_api
    mode http
    option forwardfor
    http-request set-header X-Forwarded-Proto http
    http-request set-header X-Real-IP %[src]
    http-request set-header X-Forwarded-Port ${NPM_ADMIN_PORT}
    http-response set-header X-Served-By "%[hostname]"
    server api 127.0.0.1:3000 check

backend backend_frontend
    mode http
    option forwardfor
    http-request set-header X-Forwarded-Proto http
    http-request set-header X-Real-IP %[src]
    http-request set-header X-Forwarded-Port ${NPM_ADMIN_PORT}
    http-response set-header X-Served-By "%[hostname]"
    # SPA routing - try file, then directory, then index.html
    http-request set-var(txn.path) path
    http-request set-var(txn.ext) path,field(1),reg(\.\w+)$
    http-request deny deny_status 404 if { var(txn.ext) -m end .css .js .map .png .jpg .jpeg .gif .ico .svg .woff .woff2 .ttf .eot }
    http-request set-path /%[path]/index.html if { var(txn.path) -m str / }
    http-request set-path /index.html if { var(txn.path) -m str / }
    http-request set-path /index.html if { var(txn.path) -m beg /index.html }
    http-request set-path %[path] if { var(txn.path) -m beg /index.html }
    # Remove .html extension for routing
    http-request set-path %[path,reg(\.html)$,sub()] if { var(txn.ext) -m str .html }
    http-request set-path %[path,reg(\.html)$] if { var(txn.ext) -m str .html }
    http-response set-path /[%%[txn.path]] if { var(txn.path) -m str / }
    http-request replace-path ^(/)([^/]*)(.*)$$ /%%2%%3 if { var(txn.ext) -m str .html }
    # Fallback to index.html
    errorfile 404 /etc/haproxy/errors/404-fallback.http
    http-request set-path /index.html if { path / }
    server frontend 127.0.0.1:5173 check
EOF

chmod 644 "$ADMINCFG"
log_info "Generated ${ADMINCFG} with port ${NPM_ADMIN_PORT}"
