# Admin UI - forwards port 81 to Node.js backend (port 3000)
frontend admin_ui
    bind 0.0.0.0:81
    mode http
    http-request set-header X-Forwarded-Proto http
    option forwardfor
    default_backend backend_api

backend backend_api
    option httpchk GET /health
    http-check expect status 200
    server backend1 127.0.0.1:3000 check
